name: Linux Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    if: "github.repository == 'libamtrack/library' && !contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
    name: Compile and test library
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: install necessary packages
      run: |
        sudo apt-get -y install libgsl-dev
        
    - name: autoconf
      run: autoreconf --force --install
      
    - name: configure
      run: ./configure --prefix=`pwd`/usr
      
    - name: make
      run: make -j2
      
    - name: make install
      run: make install

    - name: tests
      run: |
        ./usr/bin/amtrack_demo
        ./usr/bin/amtrack_test      
  
  python_package:
    if: "github.repository == 'libamtrack/library' && !contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
    name: test Python bindings
    
    runs-on: ubuntu-latest
    
    needs: [build_and_test]
    
    steps:
    - uses: actions/checkout@v2

    - run: echo "making python package"
