name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: install necessary packages
      run: |
        sudo apt-get -y install libgsl-dev
        
    - name: autoconf
      run: autoreconf --force --install
      
    - name: configure
      run: ./configure --prefix=`pwd`/usr
      
    - name: make
      run: make -j2
      
    - name: make install
      run: make install
      
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: tests
      run: |
        ./usr/bin/amtrack_demo
        ./usr/bin/amtrack_test

